openapi: 3.0.0
info:
  title: User Management API with Authentication
  description: A simple API to manage users with token-based authentication.
  version: "1.0.0"

paths:
  /users:
    get:
      summary: Get all users (requires token)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Token is missing or invalid
    post:
      summary: Create a new user (requires token)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
        '401':
          description: Unauthorized - Token is missing or invalid

  /users/{id}:
    get:
      summary: Get a user by ID (requires token)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single user
        '404':
          description: User not found
        '401':
          description: Unauthorized - Token is missing or invalid
    put:
      summary: Update a user by ID (requires token)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
        '404':
          description: User not found
        '401':
          description: Unauthorized - Token is missing or invalid
    delete:
      summary: Delete a user by ID (requires token)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found
        '401':
          description: Unauthorized - Token is missing or invalid

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Indicates the format (optional)

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
